feat(tsc): build clean up
shigma/yakumo pull request #7
Opened 2023-03-04 03:55 UTC by Seidko

解决一部分 #5 的问题（不知道是不是完全解决了所以暂时不 link 这个 issue 了）

如有写得不好的地方请指正qwq

2023-03-04 04:42 UTC, shigma requested changes

2023-03-04 04:42 UTC, shigma commented on packages/tsc/src/index.ts
> +  interface Arguments {
不应该有这一段，yargs-parser 自己就有类型。

2023-03-04 04:42 UTC, shigma commented on packages/tsc/src/index.ts
> +          fsp.rm(join(fullpath, 'tsconfig.temp.json')),
tsconfig.temp.json 相当于 cwd 而不是 fullpath，看下面的代码。

2023-03-04 04:42 UTC, shigma commented on packages/tsc/src/index.ts
> +        const { compilerOptions: { outDir = 'lib' }} = await load(fullpath)
这里其实有两种情况，一种是 `outDir` 一种是 `outFile`。不过只删除 `outFile` 似乎也不太好，就按你现在的来吧。

2023-03-04 04:42 UTC, shigma commented on packages/tsc/src/index.ts
> +        const { compilerOptions: { outDir = 'lib' }} = await load(fullpath)
我觉得还需要考虑 `compilerOptions` 不存在的情况。

```suggestion
        const config = await load(fullpath)
        const outDir = config.compilerOptions?.outDir || 'lib'
```

2023-03-04 04:44 UTC, shigma commented
> 解决一部分 https://github.com/shigma/yakumo/issues/5 的问题（不知道是不是完全解决了所以暂时不 link 这个 issue 了）

我觉得可以算解决。

2023-03-04 06:06 UTC, Seidko commented on packages/tsc/src/index.ts
> +          fsp.rm(join(fullpath, 'tsconfig.temp.json')),
我直接删掉这一行吧

2023-03-04 18:37 UTC, shigma reviewed
之前要删 temp 的来着，现在怎么不删了？

2023-03-04 18:37 UTC, shigma commented on packages/tsc/src/index.ts
> +        const { compilerOptions: { outDir = 'lib' } = {}} = await load(fullpath)
```suggestion
        const { compilerOptions: { outDir = 'lib' } = {} } = await load(fullpath)
```

2023-03-04 18:37 UTC, shigma commented on packages/tsc/src/index.ts
> +          fsp.rm(fullOutDir, { recursive: true }),
```suggestion
        await Promise.allSettled([
          fsp.rm(join(fullpath, outDir), { recursive: true }),
```

这样跟下一行统一比较好。

2023-03-06 07:46 UTC, shigma requested changes

2023-03-06 07:46 UTC, shigma commented on packages/tsc/src/index.ts
> +          fsp.rm(join(cwd, 'tsconfig.temp.json'))
你看我一开始的 review comment 怎么写的……

这一行逻辑跟 path 无关，那么需要写在 for 循环里执行很多遍吗？

2023-03-06 10:42 UTC, Seidko commented on packages/tsc/src/index.ts
> +          fsp.rm(join(cwd, 'tsconfig.temp.json'))
我是笨蛋😖

2023-03-06 10:45 UTC, Lipraty commented on packages/tsc/src/index.ts
> +          fsp.rm(join(cwd, 'tsconfig.temp.json'))
小笨蛋
<!-- BOT-MESSAGE-FOOTER -->
---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

2023-03-06 10:48 UTC, HsiangNianian commented on packages/tsc/src/index.ts
> +          fsp.rm(join(cwd, 'tsconfig.temp.json'))
你是笨蛋
<!-- BOT-MESSAGE-FOOTER -->
---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

2023-03-06 11:29 UTC, medicago087 commented on packages/tsc/src/index.ts
> +          fsp.rm(join(cwd, 'tsconfig.temp.json'))
你是猪
<!-- BOT-MESSAGE-FOOTER -->
---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

2023-03-06 16:39 UTC, shigma requested changes

2023-03-06 16:39 UTC, shigma commented on packages/tsc/src/index.ts
> +    fsp.rm(join(cwd, 'tsconfig.temp.json'))
await

2023-03-06 18:27 UTC, shigma requested changes
下面的 all settled 感觉仍然没写到点上：

- 如果不在乎性能的话完全可以分别写两个 `fsp.rm().catch()`
- 如果考虑性能的话，外面还有一个大大的 for 等着呢

按你的写法可以改成这样：

```ts
const tasks: Promise<any>[] = []
tasks.push(fsp.rm(temp))
for () {
  tasks.push(fsp.rm(outDir))
  tasks.push(fsp.rm(tsbuildinfo))
}
await Promise.allSettled(tasks)
```

2023-03-06 18:27 UTC, shigma commented on packages/tsc/src/index.ts
> +    await fsp.rm(join(cwd, 'tsconfig.temp.json'))
补一下 catch

2023-03-13 12:04 UTC, shigma reviewed
辛苦了，不用改了，我看看自己怎么优化一下（

2023-03-13 12:04 UTC, shigma commented on packages/tsc/src/index.ts
> +    const task: Promise<void>[] = []
```suggestion
    const task: Promise<void>[] = []
    tasks.push(fsp.rm(join(cwd, 'tsconfig.temp.json'))
```

2023-03-13 12:09 UTC, merged